import 'package:flutter/material.dart';
import '../database/db_helper.dart';
import 'poi_service.dart';

class LanguageManager {
  static final LanguageManager instance = LanguageManager._init();
  LanguageManager._init();

  String _currentLanguage = 'en';
  String get currentLanguage => _currentLanguage;

  final ValueNotifier<String> languageNotifier = ValueNotifier('en');

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'connect': 'Connect',
      'timeline': 'Timeline',
      'settings': 'Settings',
      'search_countries': 'Search countries...',
      'lg_user': 'LG USER',
      'lg_password': 'LG PASSWORD',
      'ip': 'IP',
      'lg_port': 'LG PORT',
      'screens': 'NUMBER OF SCREENS',
      'connect_button': 'CONNECT',
      'disconnect_button': 'DISCONNECT',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'about_us': 'ABOUT US',
      'help': 'HELP',
      'connection': 'CONNECTION',
      'preferences': 'PREFERENCES',
      'language': 'LANGUAGE',
      'lg_tools': 'LG TOOLS',
      'relaunch': 'RELAUNCH',
      'shutdown': 'SHUTDOWN',
      'clean_kmls': 'CLEAN KMLS',
      'clean_logos': 'CLEAN LOGOS',
      'reboot_lg': 'REBOOT LG',
      'set_refresh': 'SET SLAVES REFRESH',
      'reset_refresh': 'RESET SLAVES REFRESH',
      'show_hide_logos': 'SHOW/HIDE LOGOS',
      'show_logos': 'SHOW LOGOS',
      'logo_scale': 'LOGO SCALE',
      'past': 'PAST',
      'present': 'PRESENT',
      'future': 'FUTURE',
      'travel_lg': 'TRAVEL IN LIQUID GALAXY',
      'confirm_title': 'CONFIRMATION',
      'confirm_message': 'Are you sure you want to',
      'yes': 'YES',
      'no': 'NO',
      'generate_future': 'GENERATE FUTURE ESTIMATION',
      'regenerate_future': 'REGENERATE FUTURE ESTIMATION',
      'ai_generated': 'AI GENERATED',
      'estimation_of': 'Estimation of',
      'generating_future': 'Generating future estimation...',
      'future_success': 'Future estimation assets generated successfully!',
      'api_management': 'API MANAGEMENT',
      'image_generation_api': 'IMAGE GENERATION API',
      'model': 'MODEL',
      'save': 'SAVE',
      'api_saved_success': 'API Key saved successfully!',
      'api_saved_error': 'Please enter a valid API Key',
      'hide_comparison': 'HIDE COMPARISON',
      'compare_present': 'COMPARE WITH PRESENT',
      'stop_narration': 'STOP NARRATION',
      'ai_narration': 'AI NARRATION',
      'stop_orbit': 'STOP ORBIT',
      'orbit_around': 'ORBIT AROUND',
      'hide_statistics': 'HIDE STATISTICS',
      'show_statistics': 'SHOW PHOTO',
      'future_present_comparison': 'FUTURE + PRESENT COMPARISON',
      'past_present_comparison': 'PAST + PRESENT COMPARISON',
      'traveling_to': 'Traveling to',
      'connect_first': 'Please connect to Liquid Galaxy first',
      'comparison_hidden': 'Comparison hidden',
      'comparison_success': 'Comparison loaded successfully!',
      'orbit_stopped': 'Orbit stopped',
      'orbit_starting': 'Starting orbit around',
      'ai_disclaimer':
          'The estimation image will be different depending on the AI model that you use in your configuration',
      'additive_prompt_hint':
          'Add an additive prompt (e.g. "more trees", "cyberpunk style")...',
      'help_q1': 'How does the app work?',
      'help_a1':
          'This app allows you to control a Liquid Galaxy system and explore different places through time (Past, Present, and Future).',
      'help_q2': 'How to connect?',
      'help_a2':
          'Go to the Connection tab, enter your Liquid Galaxy user, password, IP, port, and number of screens, then press CONNECT.',
      'help_q3': 'What is the Timeline?',
      'help_a3':
          'The timeline lets you select different countries and see their most famous Points of Interest across different eras.',
      'help_q4': 'Languages',
      'help_a4':
          'You can change the app language in the Settings tab. We support English, Spanish, and Catalan.',
      'no_narration': 'No text available to narrate',
      'loading': 'LOADING...',
      'app_description_title': 'APP DESCRIPTION',
      'app_description_text':
          'Liquid Galaxy Time Machine is an interactive application designed to visualize the evolution of historical landmarks over time. Using the power of Liquid Galaxy, users can travel through past, present, and future eras, exploring how architecture and landscapes have transformed through immersive 3D visualizations and historical data.',
      'mentions_title': 'MENTIONS',
      'mention_jan': 'Jan Sánchez - App Creator',
      'mention_alfredo': 'Alfredo Bautista - Mentor',
      'mention_andreu': 'Andreu Ibañez - Mentor',
      'mention_lg': 'Liquid Galaxy Project',
      'mention_parc': 'Parc Agrobiotech Lleida',
      'mention_laboratoris': 'Laboratoris TIC',
      'fill_fields_error': 'Please fill all fields',
      'invalid_port_error': 'Invalid port',
      'connection_failed_error': 'Connection failed. Check your data.',
      'search_places': 'Search places...',
      'no_places_found': 'No places found',
      'error_loading_pois':
          'Unable to load places. Check the connection and try again.',
      'retry': 'TRY AGAIN',
      'error_prefix': 'Error',
      'english': 'English',
      'spanish': 'Spanish',
      'catalan': 'Catalan',
      'estimation_in_2100': 'in 2100',
      'united_states': 'United States',
      'france': 'France',
      'italy': 'Italy',
      'spain': 'Spain',
      'united_kingdom': 'United Kingdom',
      'germany': 'Germany',
      'greece': 'Greece',
      'egypt': 'Egypt',
      'china': 'China',
      'japan': 'Japan',
      'india': 'India',
      'brazil': 'Brazil',
      'australia': 'Australia',
      'mexico': 'Mexico',
      'peru': 'Peru',
      'canada': 'Canada',
      'summary': 'SUMMARY',
      'api_key': 'API KEY',
      'font_size': 'FONT SIZE',
      'small': 'SMALL',
      'medium': 'MEDIUM',
      'large': 'LARGE',
      'help_q5': 'AI Generation',
      'help_a5':
          'To generate future estimations, you need to configure an API Key from pollinations.ai in the Settings tab. Follow the instructions in the "API OBTAINMENT" section.',
      'kml_appearing': 'Checking 3D visualization...',
      'kml_success': '3D visualization loaded successfully!',
      'error_kml_ssh': 'SSH connection error during 3D generation',
      'error_kml_permission': 'Permission denied on Liquid Galaxy',
      'error_kml_file': 'Failed to create KML file on LG',
      'error_kml_refresh': 'Failed to update Liquid Galaxy refresh links',
      'error_kml_generic': '3D visualization failed to appear',
    },
    'es': {
      'connect': 'Conectar',
      'timeline': 'Línea de tiempo',
      'settings': 'Ajustes',
      'search_countries': 'Buscar países...',
      'lg_user': 'USUARIO LG',
      'lg_password': 'PASSWORD LG',
      'ip': 'IP',
      'lg_port': 'PUERTO LG',
      'screens': 'NÚMERO DE PANTALLAS',
      'connect_button': 'CONECTAR',
      'disconnect_button': 'DESCONECTAR',
      'connected': 'Conectado',
      'disconnected': 'Desconectado',
      'about_us': 'SOBRE NOSOTROS',
      'help': 'AYUDA',
      'connection': 'CONEXIÓN',
      'preferences': 'PREFERENCIAS',
      'language': 'IDIOMA',
      'lg_tools': 'HERRAMIENTAS LG',
      'relaunch': 'REINICIAR APP',
      'shutdown': 'APAGAR',
      'clean_kmls': 'LIMPIAR KMLS',
      'clean_logos': 'LIMPIAR LOGOS',
      'reboot_lg': 'REINICIAR LG',
      'set_refresh': 'ACTIVAR REFRESCO',
      'reset_refresh': 'DESACTIVAR REFRESCO',
      'show_hide_logos': 'MOSTRAR/OCULTAR LOGOS',
      'show_logos': 'MOSTRAR LOGOS',
      'logo_scale': 'ESCALA DE LOGOS',
      'past': 'PASADO',
      'present': 'PRESENTE',
      'future': 'FUTURO',
      'travel_lg': 'VIAJAR EN LIQUID GALAXY',
      'confirm_title': 'CONFIRMACIÓN',
      'confirm_message': '¿Estás seguro de que quieres',
      'yes': 'SÍ',
      'no': 'NO',
      'generate_future': 'GENERAR ESTIMACIÓN FUTURA',
      'regenerate_future': 'REGENERAR ESTIMACIÓN FUTURA',
      'ai_generated': 'GENERADO POR IA',
      'estimation_of': 'Estimación de',
      'generating_future': 'Generando estimación futura...',
      'future_success': '¡Recursos de estimación futura generados con éxito!',
      'api_management': 'GESTIÓN DE API',
      'image_generation_api': 'API DE GENERACIÓN DE IMAGEN',
      'model': 'MODELO',
      'save': 'GUARDAR',
      'api_saved_success': '¡API Key guardada con éxito!',
      'api_saved_error': 'Por favor, introduce una API Key válida',
      'hide_comparison': 'OCULTAR COMPARATIVA',
      'compare_present': 'COMPARAR CON EL PRESENTE',
      'stop_narration': 'DETENER NARRACIÓN',
      'ai_narration': 'NARRACIÓN POR IA',
      'stop_orbit': 'DETENER ÓRBITA',
      'orbit_around': 'ORBITAR ALREDEDOR',
      'hide_statistics': 'OCULTAR ESTADÍSTICAS',
      'show_statistics': 'MOSTRAR FOTO',
      'future_present_comparison': 'COMPARATIVA FUTURO + PRESENTE',
      'past_present_comparison': 'COMPARATIVA PASADO + PRESENTE',
      'traveling_to': 'Viajando a',
      'connect_first': 'Por favor, conéctate a Liquid Galaxy primero',
      'comparison_hidden': 'Comparativa oculta',
      'comparison_success': '¡Comparativa cargada con éxito!',
      'orbit_stopped': 'Órbita detenida',
      'orbit_starting': 'Iniciando órbita alrededor de',
      'ai_disclaimer':
          'La imagen de estimación variará según el modelo de IA que utilices en tu configuración',
      'additive_prompt_hint':
          'Añade un prompt adicional (ej. "más árboles", "estilo cyberpunk")...',
      'help_q1': '¿Cómo funciona la aplicación?',
      'help_a1':
          'Esta aplicación te permite controlar un sistema Liquid Galaxy y explorar diferentes lugares a través del tiempo (Pasado, Presente y Futuro).',
      'help_q2': '¿Cómo conectarse?',
      'help_a2':
          'Ve a la pestaña Conexión, introduce tu usuario de Liquid Galaxy, contraseña, IP, puerto y número de pantallas, luego pulsa CONECTAR.',
      'help_q3': '¿Qué es la Línea de Tiempo?',
      'help_a3':
          'La línea de tiempo te permite seleccionar diferentes países y ver sus Puntos de Interés más famosos a través de diferentes épocas.',
      'help_q4': 'Idiomas',
      'help_a4':
          'Puedes cambiar el idioma de la aplicación en la pestaña Ajustes. Soportamos inglés, español y catalán.',
      'no_narration': 'No hay texto disponible para narrar',
      'loading': 'CARGANDO...',
      'app_description_title': 'DESCRIPCIÓ DE LA APP',
      'app_description_text':
          'Liquid Galaxy Time Machine es una aplicación interactiva diseñada para visualizar la evolución de monumentos históricos a lo largo del tiempo. Utilizando el poder de Liquid Galaxy, los usuarios pueden viajar a través de las eras pasada, presente y futura, explorando cómo la arquitectura y los paisajes se han transformado a través de visualizaciones 3D inmersivas y datos históricos.',
      'mentions_title': 'MENCIONES',
      'mention_jan': 'Jan Sánchez - Creador de la App',
      'mention_alfredo': 'Alfredo Bautista - Mentor',
      'mention_andreu': 'Andreu Ibañez - Mentor',
      'mention_lg': 'Liquid Galaxy Project',
      'mention_parc': 'Parc Agrobiotech Lleida',
      'mention_laboratoris': 'Laboratoris TIC',
      'fill_fields_error': 'Por favor, rellena todos los campos',
      'invalid_port_error': 'Puerto no válido',
      'connection_failed_error': 'Error de conexión. Comprueba tus datos.',
      'search_places': 'Buscar lugares...',
      'no_places_found': 'No se han encontrado lugares',
      'error_loading_pois':
          'No se han podido cargar los lugares. Comprueba la conexión e inténtalo de nuevo.',
      'retry': 'REINTENTAR',
      'error_prefix': 'Error',
      'english': 'Inglés',
      'spanish': 'Español',
      'catalan': 'Catalán',
      'estimation_in_2100': 'en 2100',
      'united_states': 'Estados Unidos',
      'france': 'Francia',
      'italy': 'Italia',
      'spain': 'España',
      'united_kingdom': 'Reino Unido',
      'germany': 'Alemania',
      'greece': 'Grecia',
      'egypt': 'Egipto',
      'china': 'China',
      'japan': 'Japón',
      'india': 'India',
      'brazil': 'Brasil',
      'australia': 'Australia',
      'mexico': 'México',
      'peru': 'Perú',
      'canada': 'Canadá',
      'summary': 'RESUMEN',
      'api_key': 'CLAVE API',
      'font_size': 'TAMAÑO DE FUENTE',
      'small': 'PEQUEÑO',
      'medium': 'MEDIANO',
      'large': 'GRANDE',
      'help_q5': 'Generación por IA',
      'help_a5':
          'Para generar estimaciones futuras, necesitas configurar una API Key de pollinations.ai en la pestaña de Ajustes. Sigue las instrucciones en la sección "OBTENCIÓN DE API".',
      'kml_appearing': 'Comprobando visualización 3D...',
      'kml_success': '¡Visualización 3D cargada correctamente!',
      'error_kml_ssh': 'Error de conexión SSH durante la generación 3D',
      'error_kml_permission': 'Permiso denegado en Liquid Galaxy',
      'error_kml_file': 'Error al crear el archivo KML en LG',
      'error_kml_refresh': 'Error al actualizar los enlaces de Liquid Galaxy',
      'error_kml_generic': 'La visualización 3D no ha aparecido',
    },
    'ca': {
      'connect': 'Connectar',
      'timeline': 'Línia de temps',
      'settings': 'Configuració',
      'search_countries': 'Cercar països...',
      'lg_user': 'USUARI LG',
      'lg_password': 'CONTRASENYA LG',
      'ip': 'IP',
      'lg_port': 'PORT LG',
      'screens': 'NOMBRE DE PANTALLES',
      'connect_button': 'CONNECTAR',
      'disconnect_button': 'DESCONNECTAR',
      'connected': 'Connectat',
      'disconnected': 'Desconnectat',
      'about_us': 'SOBRE NOSALTRES',
      'help': 'AJUDA',
      'connection': 'CONNEXIÓ',
      'preferences': 'PREFERÈNCIES',
      'language': 'IDIOMA',
      'lg_tools': 'EINES LG',
      'relaunch': 'REINICIAR APP',
      'shutdown': 'APAGAR',
      'clean_kmls': 'NETEJAR KMLS',
      'clean_logos': 'NETEJAR LOGOS',
      'reboot_lg': 'REINICIAR LG',
      'set_refresh': 'ACTIVAR REFRESCO',
      'reset_refresh': 'DESACTIVAR REFRESCO',
      'show_hide_logos': 'MOSTRAR/OCULTAR LOGOS',
      'show_logos': 'MOSTRAR LOGOS',
      'logo_scale': 'ESCALA DE LOGOS',
      'past': 'PASSAT',
      'present': 'PRESENT',
      'future': 'FUTUR',
      'travel_lg': 'VIATJAR A LIQUID GALAXY',
      'confirm_title': 'CONFIRMACIÓ',
      'confirm_message': 'Estàs segur que vols',
      'yes': 'SÍ',
      'no': 'NO',
      'generate_future': 'GENERAR ESTIMACIÓ FUTURA',
      'regenerate_future': 'REGENERAR ESTIMACIÓ FUTURA',
      'ai_generated': 'GENERAT PER IA',
      'estimation_of': 'Estimació de',
      'generating_future': 'Generant estimació futura...',
      'future_success': 'Recursos d\'estimació futura generats correctament!',
      'api_management': 'GESTIÓ D\'API',
      'image_generation_api': 'API DE GENERACIÓ D\'IMATGE',
      'model': 'MODEL',
      'save': 'GUARDAR',
      'api_saved_success': 'API Key guardada correctament!',
      'api_saved_error': 'Per favor, introdueix una API Key vàlida',
      'hide_comparison': 'OCULTAR COMPARATIVA',
      'compare_present': 'COMPARAR AMB EL PRESENT',
      'stop_narration': 'ATURAR NARRACIÓ',
      'ai_narration': 'NARRACIÓ PER IA',
      'stop_orbit': 'ATURAR ÒRBITA',
      'orbit_around': 'ORBITAR AL VOLTANT',
      'hide_statistics': 'OCULTAR ESTADÍSTIQUES',
      'show_statistics': 'MOSTRAR FOTO',
      'future_present_comparison': 'COMPARATIVA FUTUR + PRESENT',
      'past_present_comparison': 'COMPARATIVA PASSAT + PRESENT',
      'traveling_to': 'Viatjant a',
      'connect_first': 'Per favor, connecta\'t a Liquid Galaxy primer',
      'comparison_hidden': 'Comparativa oculta',
      'comparison_success': 'Comparativa carregada correctament!',
      'orbit_stopped': 'Òrbita aturada',
      'orbit_starting': 'Iniciant òrbita al voltant de',
      'ai_disclaimer':
          'La imatge d\'estimació serà diferent depenent del model d\'IA que utilitzis a la teva configuració',
      'additive_prompt_hint':
          'Afegeix un prompt addicional (ex. "més arbres", "estil cyberpunk")...',
      'help_q1': 'Com funciona l\'aplicació?',
      'help_a1':
          'Aquesta aplicació et permet controlar un sistema Liquid Galaxy i explorar diferents llocs a través del temps (Passat, Present i Futur).',
      'help_q2': 'Com connectar-se?',
      'help_a2':
          'Ves a la pestanya Connexió, introdueix el teu usuari de Liquid Galaxy, contrasenya, IP, port i nombre de pantalles, després prem CONNECTAR.',
      'help_q3': 'Què és la Línia de Temps?',
      'help_a3':
          'La línia de temps et permet seleccionar diferents països i veure els seus Punts d\'Interès més famosos a través de diferents èpoques.',
      'help_q4': 'Idiomes',
      'help_a4':
          'Pots canviar l\'idioma de l\'aplicació a la pestanya Configuració. Suportem anglès, espanyol i català.',
      'no_narration': 'No hi ha text disponible per narrar',
      'loading': 'CARREGANT...',
      'app_description_title': 'DESCRIPCIÓ DE L\'APP',
      'app_description_text':
          'Liquid Galaxy Time Machine és una aplicació interactiva dissenyada per visualitzar l\'evolució de monuments històrics al llarg del temps. Utilitzant el poder de Liquid Galaxy, els usuaris poden viatjar a través de les eres passada, present i futura, explorant com l\'arquitectura i els paisatges s\'han transformat a través de visualitzacions 3D immersives i dades històriques.',
      'mentions_title': 'MENCIONS',
      'mention_jan': 'Jan Sánchez - Creador de l\'App',
      'mention_alfredo': 'Alfredo Bautista - Mentor',
      'mention_andreu': 'Andreu Ibañez - Mentor',
      'mention_lg': 'Liquid Galaxy Project',
      'mention_parc': 'Parc Agrobiotech Lleida',
      'mention_laboratoris': 'Laboratoris TIC',
      'fill_fields_error': 'Per favor, emplena tots els camps',
      'invalid_port_error': 'Port no vàlid',
      'connection_failed_error': 'Error de connexió. Comprova les teves dades.',
      'search_places': 'Cercar llocs...',
      'no_places_found': 'No s\'han trobat llocs',
      'error_loading_pois':
          'No s\'han pogut carregar els llocs. Comprova la connexió i torna-ho a provar.',
      'retry': 'REPROVAR',
      'error_prefix': 'Error',
      'english': 'Anglès',
      'spanish': 'Espanyol',
      'catalan': 'Català',
      'estimation_in_2100': 'al 2100',
      'united_states': 'Estats Units',
      'france': 'França',
      'italy': 'Itàlia',
      'spain': 'Espanya',
      'united_kingdom': 'Regne Unit',
      'germany': 'Alemanya',
      'greece': 'Grècia',
      'egypt': 'Egipte',
      'china': 'Xina',
      'japan': 'Japó',
      'india': 'Índia',
      'brazil': 'Brasil',
      'australia': 'Austràlia',
      'mexico': 'Mèxic',
      'peru': 'Perú',
      'canada': 'Canadà',
      'summary': 'RESUM',
      'api_key': 'CLAU API',
      'font_size': 'MIDA DE FONT',
      'small': 'PETIT',
      'medium': 'MITJÀ',
      'large': 'GRAN',
      'help_q5': 'Generació per IA',
      'help_a5':
          'Per generar estimacions futures, necessites configurar una API Key de pollinations.ai a la pestanya de Configuració. Segueix les instruccions a la secció "OBTENCIÓ D\'API".',
      'kml_appearing': 'Comprovant visualització 3D...',
      'kml_success': 'Visualització 3D carregada correctament!',
      'error_kml_ssh': 'Error de connexió SSH durant la generació 3D',
      'error_kml_permission': 'Permís denegat a Liquid Galaxy',
      'error_kml_file': 'Error en crear l\'arxiu KML a LG',
      'error_kml_refresh': 'Error en actualitzar els enllaços de Liquid Galaxy',
      'error_kml_generic': 'La visualització 3D no ha aparegut',
    },
  };

  Future<void> init() async {
    final savedLang = await DatabaseHelper.instance.getSetting('language');
    if (savedLang != null) {
      _currentLanguage = savedLang;
      languageNotifier.value = savedLang;
    }
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  Future<void> changeLanguage(String langCode) async {
    if (_translations.containsKey(langCode)) {
      _currentLanguage = langCode;
      languageNotifier.value = langCode;
      await DatabaseHelper.instance.saveSetting('language', langCode);
      // Clear POI cache to force reload with new language files
      POIService.clearCache();
    }
  }
}
